import Head from "next/head";

import Navbar from "components/navbar";
import Header from "components/header";
import Main from "components/main";
import Sidebar from "components/sidebar";

import stl from "./index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>HomeHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={stl.main}>
        <Navbar />
        <div className={stl.container}>
          <Header />
          <div className={stl.center}>
            <Main />
            <Sidebar />
          </div>
        </div>
      </main>
    </>
  );
}
